<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/1/13 0013
 * Time: 11:12
 */

namespace common\models;


class UserCollection extends BaseActiveRecord
{
    const ARTICLE_TYPE = 1;

    public function rules() {
        return [
            [['type', 'type_id', 'user_id'], 'safe']
        ];
    }

    public static function isArticleCollectedByUser($userId, $articleId) {
        return self::find()->where([
            'user_id' => $userId,
            'type_id' => $articleId,
            'type' => self::ARTICLE_TYPE
        ])->exists();
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->create_by = time();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}